### ISSUE TITLE
Signed certificates?

### ISSUE THREAD

**Issue by bserem** [mpyw/php-hyper-builtin-server#6]
Is it possible to server a signed certificate? One that will not display warnings on browsers?

For example, firefox now reports:

```
Your connection is not secure
localhost:8081 uses an invalid security certificate.
The certificate is not trusted because it is self-signed.
```

Thanks

**Comment by mpyw** [comment]
[Certificates for localhost - Let's Encrypt - Free SSL/TLS Certificates](https://letsencrypt.org/docs/certificates-for-localhost/)

**Comment by bserem** [comment]
Thanks!

**Comment by antonkomarev** [comment]
I've wrote a small out of the box solution to generate signed certificate for this server: https://github.com/pric/pric
